### ISSUE TITLE
Creating a new API at Apiary

### ISSUE THREAD

**Issue by zdne** [apiaryio/apiary-client#62]
An attempt to create a new API from a local apiary.apib file fails with 

```
zdenek$ apiary publish --api-name=mynewapi123
Apiary service responded with an error: 404 Resource Not Found
```

Please provide the means to create a new API or at least, provide a clear information that API has to be first created manually at Apiary.

**Comment by jrep** [comment]
There is a risk of interaction with the "automatic uniquification" feature (appending a number) of the website "Create New" feature. Uniquification is a good feature when you know there's a human reading the return, but a bad feature for nattended automation. A command-line tool is used both interactively and unattendedly, though, so things are a bit ambiguous.

Because unexpected renaming is a major problem for automated use, while collision-failure is only an annoyance for interactive use (and, I confess, because unattended automation is my primary use-case), I think this CLI addition must either not do uniquification, or at the least provide an override parameter to force behavior. If there's a parameter, I'm neutral on which behavior should be the default.

Related: at the moment, it's very hard for an automated process to discern whether a `apiary publish` failed due to there being no such api-name, or due to some other reason ("no such api-name" is signaled by a 404, which is reasonable, but the 404 is buried in string output to stderr -- again, proper for interactive use but awkward for automation.

**Comment by tu1ly** [comment]
https://github.com/apiaryio/apiary-client/pull/127
