### ISSUE TITLE
rest-client 1.7.3 is has a security vulnerability

### ISSUE THREAD

**Issue by RobinClowers** [apiaryio/apiary-client#91]
https://isitvulnerable.com/vulns/557513c4-f150-429c-b7f2-58e21936a535

**Comment by jrep** [comment]
On Aug 7, 2015, at 10:22 AM, Robin Clowers <notifications@github.com> wrote:
> 
> https://isitvulnerable.com/vulns/557513c4-f150-429c-b7f2-58e21936a535 <https://isitvulnerable.com/vulns/557513c4-f150-429c-b7f2-58e21936a535>
> 

Reported fixed in 1.8.0: https://github.com/rest-client/rest-client/issues/369 <https://github.com/rest-client/rest-client/issues/369>

... although there's a report that this breaks something else, https://github.com/rest-client/rest-client/issues/406 <https://github.com/rest-client/rest-client/issues/406>



--
Jack Repenning
Jack@netgate.net
